application: login-sistem
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /signup
  script: main.app
  secure: always

- url: /login
  script: main.app
  secure: always

- url: /forgot
  script: main.app
  secure: always

- url: /assets
  static_dir: assets

- url: .*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.1"
